### ISSUE TITLE
scheduler in StreamingContext cannot be accessed

### ISSUE THREAD

**Issue by trienism** [mkuthan/example-spark#1] opened 2015-03-10 22:59 UTC
Hi,

How are you accessing the scheduler from the ssc object without error? 

ClockWrapper.scala 
```
  private val manualClock = ssc.scheduler.clock.asInstanceOf[ManualClock]
```

From the scala console

```
scala> import org.apache.spark.streaming.util.ManualClock
import org.apache.spark.streaming.util.ManualClock

scala> ssc.scheduler
<console>:91: error: value scheduler in class StreamingContext cannot be accessed in org.apache.spark.streaming.StreamingContext
              ssc.scheduler
```

**Comment by mkuthan** [comment] 2015-03-11 07:18
ManualClock is marked as package private. Look at package of ClockWrapper, the class is located under   org.apache.spark.streaming. Ugly hack, isn't it?

**Comment by trienism** [comment] 2015-03-11 18:50
Yup, that is an ugly hack :-) Although the rest of the code is pretty clean and helpful. Thanks!

**Comment by mkuthan** [comment] 2015-03-11 20:26
It's a feature not a bug ;-)

**Closed by mkuthan** 2015-03-11 20:26 UTC
